
<../config.mk

results/%_tagged.bam:	data/%_R1.fastq.gz data/%_R2.fastq.gz
	$DDS_HOME'ddSeeker.py' \
		--input $prereq \
		--output $target'.build' \
		--cores $NC \
	&& mv $target'.build' $target

clean:V:
        bin/targets | xargs rm -rf
        rm -rf results/
