results/%.aligned.bam:	data/%.aligned.sam
	set -x
	mkdir -p results
	picard-tools \
		SortSam \
		I=$prereq \
		O=$target'.build.bam' \
		SORT_ORDER=queryname\
	&& mv $target'.build.bam' $target

clean:V:
		bin/targets | xargs rm -rf
		rm -rf results/
