<../config.mk

results/%.gen_exon_tged.bam:	data/%.merged.bam
	set -x
	mkdir -p results
	$DST_HOME'TagReadWithGeneExonFunction' \
		INPUT=$prereq \
		OUTPUT=$target'.build' \
		ANNOTATIONS_FILE=$GTF \
		TAG=GE \
	&& mv $target'.build' $target

clean:V:
        bin/targets | xargs rm -rf
        rm -rf results/
