<../config.mk

JAVA_OPTIONS='-Xmx500m'

results/%.fastq: data/%_tagged_filtered.bam
	set -x
	mkdir -p results
	picard-tools \
		SamToFastq \
		I=$prereq \
		FASTQ=$target'.build' \
	&& mv $target'.build' $target

clean:V:
		bin/targets | xargs rm -rf
		rm -rf results/
